settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
schema:
- name: /Users/senhaoyang/go/src/github.com/larryyangsen/chat
  path: /Users/senhaoyang/go/src/github.com/larryyangsen/chat
  commands:
    fmt:
      status: true
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - src
    - dist
    - node_modules
    - .cache
- name: /Users/senhaoyang/go/src/github.com/larryyangsen/chat
  path: /Users/senhaoyang/go/src/github.com/larryyangsen/chat
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
